name: Update latest

on:
  schedule:
   - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-latest:
    name: Update latest
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add and/or update test environments
        run: |
          git config user.name kittenoak
          git config user.email kittenoak@users.noreply.github.com
          
          export PRERELEASE=$(pip index --pre versions aqt | perl -ne 'm/aqt \((2.1.[a-z0-9]+)\)/ && print "$1"')
          python .github/workflows/latest.py update-prerelease $PRERELEASE \
            && git add tox.ini .github/workflows/main.yml \
            && git commit -am "Tests: update pre-release env with Anki $PRERELEASE" \
            && export PRERELEASE_TITLE="Update pre-release test environment with Anki $PRERELEASE" \
            || true
          
          export STABLE=$(pip index versions aqt | perl -ne 'm/aqt \((2.1.[a-z0-9]+)\)/ && print "$1"')
          python .github/workflows/latest.py add-stable $STABLE \
            && git add tox.ini .github/workflows/main.yml \
            && git commit -am "Tests: add new environment for Anki $STABLE" \
            && export STABLE_TITLE="Add new test environment for Anki $STABLE" \
            || true

          export PR_TITLE="$PRERELEASE_TITLE; $STABLE_TITLE"         
          export PR_TITLE=$(echo "$PR_TITLE" | sed -r 's/^[ ;]+//; s/[ ;]+$//; s/; A/; a/')
          echo "PR_TITLE=$PR_TITLE" >> "$GITHUB_ENV"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.KITTENOAK_PAT }}
          push-to-fork: kittenoak/anki-wallpaper
          title: ${{ env.PR_TITLE }}
          delete-branch: true
